### ISSUE TITLE
combine duplicated DATA and FETCH command docs

### ISSUE THREAD

**Issue by crotwell** [FDSN/SeedLink#10]
Currently DATA and FETCH are listed twice each, with different arguments. This feels confusing to me as looking at the second entry it looks like "seq" is required, but actually isn't.

Something like this conveys the arguments better I think:
```
DATA [seq [start_time [end_time]]]
```

I realize the split is trying to make clear that start_time and end_time can only be used if CAP:TIME, but feel that would be better to document in the textual description instaed of on the command listing.

**Comment by andres-h** [comment]
### Feedback from proposal team

Agreed with submitter that this could be more clearly presented in the specification.

### Change of specification

TBD

**Comment by crotwell** [comment]
+1 on change
