### ISSUE TITLE
README.md: broken link to doc

### ISSUE THREAD

**Issue by petrrr** [FDSN/SeedLink#11]
The README contains a link to documentation which seems broken.
Could this be fixed?

**Comment by crotwell** [comment]
I think the idea is that it can't be live on docs.fdsn.org until it is an accepted spec, so kind of a placeholder I guess. 

Changing the readme to link to 
https://seedlink.readthedocs.io/en/latest/index.html
until then might be helpful.

**Comment by chad-earthscope** [comment]
As clarified in the README, the link will work when the specification is in place.

For the moment, I've put [seedlink.readthedocs.io/](https://seedlink.readthedocs.io/) in the repo URL box to make it findable until then.
