### ISSUE TITLE
Question: GETCAPABILITIES vs INFO

### ISSUE THREAD

**Issue by CharlesBlais** [FDSN/SeedLink#14]
As part of https://seedlink.readthedocs.io/en/latest/protocol.html, it states:

> GETCAPABILITIES
> returns space-separated server capabilities ([Capabilities](https://seedlink.readthedocs.io/en/latest/protocol.html#capabilities)) as a single line terminated by <cr><lf>.
> 
> INFO item [station_pattern [stream_pattern*[.*format_subformat_pattern]]]
> requests information about the server in JSON format

It seems GETCAPABILITIES and INFO could be used for the same purpose  As the description states, both return information about the server.  Should they maybe be merged?

Also, for INFO, would it help if the currently authenticated user name be part of the response?  Much like “whoami” on Linux.  That might help to determine "why am not seeing the station" because of the required AUTH command for certain stations.

**Comment by crotwell** [comment]
I agree, `INFO CAPABILITIES` seems like a more natural way to do this than a separate command. 

And I think the response of GETCAPABILITIES is effectively also currently included in the response to HELLO. It is needed there so clients can determine which protocol version is supported.

The json schema would also need to be updated.

**Comment by andres-h** [comment]
### Feedback from proposal team

Agreed on dropping GETCAPABILITIES.

### Change of specification

Remove all references to GETCAPABILITIES.

**Comment by crotwell** [comment]
+1 on change
