### ISSUE TITLE
Suggestion: logging

### ISSUE THREAD

**Issue by CharlesBlais** [FDSN/SeedLink#15]
It would be great to see a section on logging.  More importantly logging formats and its content.  My main interest is logging on cyber-security elements such as ERROR, failed attempts, etc.  Documenting logging format might help guide implementation of SIEM solutions which many institutes have either implemented or looking into.  For example,  Splunk of which some of the US folks are doing.

**Comment by crotwell** [comment]
Do you feel that is needed in the protocol specification, or is that an implementation issue?

**Comment by CharlesBlais** [comment]
Ah right, oops skipped a step, implementation
