### ISSUE TITLE
Station and Stream ID selection

### ISSUE THREAD

**Issue by djeastonca** [FDSN/SeedLink#20]
Was it considered to use regular expressions for station and stream ID selection to provide additional flexibility? It is arguably overkill for SeedLink use cases, but, on the other hand, anyone designing such an expression has to be familiar with the basics of regular expressions anyway in order to understand what the SeedLink documentation means by "...the pattern is anchored to the beginning and end of string". Everyone now has ready access to AI-based regular expression generation and it would allow server implementations to benefit from existing regex libraries and reduce custom code.

**Comment by crotwell** [comment]
Personally I think regular expressions would be better, but I think the glob style patterns are for backwards compatibility, so best to keep them. Regular expressions could be supported via an optional capability/command I suppose, but not sure if it is worth adding it to the specification.

**Comment by andres-h** [comment]
### Feedback from proposal team

Regular expressions would add complexity and potential security risk that would be hard to justify.
