### ISSUE TITLE
Specify JWT as authentication type, remove reservation for TOKEN

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/SeedLink#22]
Specify JWT, for [JSON Web Token](https://jwt.io/), as an authentication type as follows:

`AUTH JWT token`

which is in addition to the defined `USERPASS` authentication type.

Also, remove the reservation of `TOKEN` which is too generic and likely will not ever be used.

**Comment by andres-h** [comment]
### Feedback from proposal team

Agreed

### Change of specification

~Type TOKEN is reserved, but not specified.~ → If type is JWT, then argument is JSON Web Token as specified by RFC 7519.

**Comment by crotwell** [comment]
+1 on change
