### ISSUE TITLE
add connections as object to schema

### ISSUE THREAD

**Issue by crotwell** [FDSN/SeedLink#26]
Output of INFO CONNECTIONS is implementation specific, but might be helpful to add at least a top level object to hold it. 

Perhaps add to schema:
```
        "connections": {
            "description": "Connections to the server. Contents are implementation specific",
            "type": "object",
            "additionalProperties: true
        },
```

**Comment by andres-h** [comment]
Agreed if JSON schema allows implementation specific contents.

**Comment by crotwell** [comment]
Yes, I think `"additionalProperties: true` means additional keys can be added into the `connections` object without being invalid for the schema. We just force the `connections` key to have an object as its value.

**Comment by crotwell** [comment]
+1 on change
