### ISSUE TITLE
Suggestion: be explicit on how custom Source Identifiers are handled 

### ISSUE THREAD

**Issue by luca-s** [FDSN/SeedLink#3]
I have one suggestion regarding the paragraph "Station ID and streamID". In there the expected station ID and stream ID format is discussed (NET_STA and LOC_B_S_SS). I would suggest to add a sentence that explains how to deal with custom source identifiers that do not follow the FDSN format. For example, stating that custom (that do not follow the format) source identifiers are not supported would suffice.

**Comment by andres-h** [comment]
### Feedback from proposal team

The protocol specification should not place requirements on station and stream IDs.  Contrary to the suggestion in the ticket, we should explicitly state that these are agnostic to other standards, and the miniSEED identifiers are the expected use case with those data payloads but that others may be used in the future, or within closed ecosystems.

### Change of specification

Add extended explanation to “Station ID and stream ID”.

**Comment by crotwell** [comment]
+1 on proposed change.
