### ISSUE TITLE
flowchart has FETCH, but should use ENDFETCH 

### ISSUE THREAD

**Issue by crotwell** [FDSN/SeedLink#44]
https://seedlink.readthedocs.io/en/draft/protocol.html#handshaking-flowchart

In dial-up mode, change FETCH to DATA and END to ENDFETCH

**Comment by andres-h** [comment]
Fixed.

Also changed "GETCAPABILITIES" to "INFO CAPABILITIES" as suggested in #14.

**Comment by crotwell** [comment]
+1 on proposed change.
