### ISSUE TITLE
Missing JSON Schemma for INFO  CAPABILITIES

### ISSUE THREAD

**Issue by marcelobianchi** [FDSN/SeedLink#46]
As proposed by Issue #14 the INFO command should be used to get a list of server CAPABILITIES but "Appendix B. JSON schema" is missing the expected JSON schema for this request type.

**Comment by andres-h** [comment]
https://github.com/FDSN/SeedLink/pull/47 adds "capability" as a simple list of strings.

**Comment by chad-earthscope** [comment]
Thanks @andres-h.  I merged the PR before noticing that the addition when into the .rst document for rendering.  I think it is also important to maintain the JSON schema in a separate file that can be used directly by software for validation.  A stand-alone schema file already exists here:

https://github.com/FDSN/SeedLink/blob/main/docs/seedlink.schema.json

Ideally, this stand-along file would be included directly into the .rst, and to avoid defining this schema in two different places.

**Comment by andres-h** [comment]
I forgot about the standalone schema file. It has now been updated and included in the document directly (draft branch). I also fixed some minor rst errors.

**Comment by chad-earthscope** [comment]
Thanks @andres-h .  Changes in `draft` have been reviewed and pushed to `main`, and rendering at RTD looks good: https://seedlink.readthedocs.io/en/latest/protocol.html#appendix-b-json-schema

Two additions that I think would be useful:
1.  a link to download the schema from the specification, or at least a link to the repository with the file, so developers are not cutting and pasting the schema from the spec for programmatic use.  
2. a schema version number (I'm not sure where to put it, for miniSEED v3 I put it in the file name), in case we ever want to add fields or change them in the future.
